# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - /home/admin/database/postgres:/var/lib/postgresql/data